version: "3"
services:
  app:
    build: .
    image: 001993/laravel-project
    container_name: app
    restart: unless-stopped
    environment: 
      DB_HOST: db
      DB_PASSWORD: secret
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build :
      context: .
      dockerfile: Dockerfile_Nginx
    image: 001993/nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - app

  database:
    image: mysql:5.7.22
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
  
volumes:
  dbdata:
    driver: local

