version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./src
    image: 001993/laravel-project
    container_name: app
    restart: unless-stopped
    environment: 
      DB_HOST: db
      DB_PASSWORD: secret
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - ./src:/var/www
      - ./src/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build :
      dockerfile: Dockerfile.dev
      context: ./
    image: 001993/nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./conf.d:/etc/nginx/conf.d/

  database:
    image: mysql:5.7.22
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
  
volumes:
  dbdata:
    driver: local

